name: Test

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build packages
        run: yarn
      - name: Build action
        run: yarn build
      - name: Run action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_DIR: "temp"
          SUMMARY_TITLE: "Test summary"
